version: '3'

networks:
    nginx-php82-mysql8-node: 

services:
    #nginx
    nginx-service:
        image: nginx:latest
        # image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./scrapper:/scrapper
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
            - node-service
        networks:
            - nginx-php82-mysql8-node
    #php
    php82-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php82-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php82-mysql8-node

    #mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            - nginx-php82-mysql8-node
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret

    #node
    node-service:
        # platform: linux/x86_64
        # image: node
        build:
            context: ./scrapper
            dockerfile: Dockerfile
        container_name: node-container
        ports:
            - "4000:4000"
        volumes:
            - ./scrapper:/scrapper
        # working_dir: /var/www/scrapper
        networks:
            - nginx-php82-mysql8-node